---
title: Otaku Showboat
timezone: UTC -5:00
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: otakushowboat@gmail.com
description: Official Blog of Otaku Showboat.
baseurl: ''
url: 'https://www.otakushowboat.com/'
twitter_username: OtakuShowboat
github_username: OtakuShowboat
markdown: kramdown
kramdown: 
  parse_block_html: true
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
permalink: "/otaku-blog/:year/:month/:day/:title/"