---
title: Otaku Showboat
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: otakushowboat@gmail.com
description: Official Blog of Otaku Showboat.
baseurl: ''
url: ''
twitter_username: OtakuShowboat
github_username: OtakuShowboat
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
permalink: "/otaku-blog/:year/:month/:day/:title/"
